apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data-pv1
  labels:
    app: elastic-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/elastic


