options:
  machineType: 'N1_HIGHCPU_8'
steps:
  - name: 'gcr.io/$PROJECT_ID/scala-sbt'
    args: ['thrall/docker:publishLocal']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'create', '--name', 'multiarch', '--driver', 'docker-container', '--use']
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'buildx', 'build', '--platform=linux/amd64,linux/arm64', 'thrall/target/docker/stage', '-t', 'eu.gcr.io/$PROJECT_ID/thrall:$BRANCH_NAME', '--push']
